name: Deploy Blog

on:
  push:
    branches: [ main ] # 监听 main 分支的变动

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 3. 设置 Node 环境 (关键修改：禁用了缓存！)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'pnpm'  <-- ⚠️ 这一行被注释掉了，为了强制修复缓存报错，请不要解开！

      # 4. 安装依赖并构建
      - name: Install and Build
        run: |
          pnpm install
          pnpm docs:build
        # VitePress 默认输出目录是 docs/.vitepress/dist

      # 5. 部署到服务器
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:  # 👈哪怕这里以前写的是 env，现在请改成 with
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "docs/.vitepress/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/docker/nginx/html/blog/"
          EXCLUDE: "/node_modules/"